INSERT INTO BOOK (BOOK_ID, TITLE) VALUES (NULL, 'The Three Body Problem');
INSERT INTO BOOK (BOOK_ID, TITLE) VALUES (NULL, 'Ancillary Justice');
INSERT INTO BOOK (BOOK_ID, TITLE) VALUES (NULL, 'The Windup Girl');
INSERT INTO BOOK (BOOK_ID, TITLE) VALUES (NULL, 'The City & The City');
